original_to_chinese_recipe_ing = {
    "tofu": "mapo tofu",
    "white rice": "jasmine scented rice",
    'rice': 'Yangchow fried rice',
    "corn": "bok choy",
    "ice cream": "baobing",
    "tea": "chinese tea",
    "sausage": "lap ceung",
    "salsa" : "mala sauce",
    'potato': 'taro root',
    "maple sauce" : "mala sauce",
    "maple syrup" : "chinese mala syrup",
    "spaghetti pasta": "lo mein",
    "spaghetti": "lo mein",
    "vinegar": "black vinegar",
    "red pepper flakes": "dried chili flakes",
    'pepper': 'tien tsin pepper',
    "italian parsley": "cilantro",
    "parmigiano-reggiano cheese": "fermented bean curd",
    "pasta": "lo mein",
    "noodles": "lo mein",
    "mushrooms": "shiitake mushrooms",
    "salad": "malatang",
    "quesadilla": "xian bing",
    "Burger": "chinese hamburger",
    "french pancake": "jian bing",
    "meat sauce": "da lu mian",
    "churro": "you tiao",
    "pizza": "scallion pancake",
    "wine": "shaoxing wine",
    "olive oil": "peanut oil",
    "burger": " chinese burger",
    "vegetable oil": "peanut oil",
    "canola oil": "peanut oil",
    "peanut oil": "peanut oil",
    "coconut oil": "peanut oil",
    "corn oil": "peanut oil",
    "sunflower oil": "peanut oil",
    "safflower oil": "peanut oil",
    "chicken nuggets": "chicken balls",
    "chicken": 'orange chicken',
    "jerky": "bak kwa",
    "tofu": "mapo doufu",
    "meat": "bakkwa",
    "lamb": "lamb broth",
    "pasta": "lo mein",
    "sauce": "hoisin sauce",
    "shrimp": "cha jang mein",
    "dressing": 'ginger dressing',
    'beef': 'mongolian beef',
    'pork': 'moo shu pork',
    'duck': 'peking roasted duck',
    'shrimp': 'fried shrimp with cashew nuts',
    'lettuce': 'stir-fried garlic lettuce',
    'eggplant': 'japanese eggplant',
    'cabbage': 'chinese cabbage',
    'bean': 'yardlong bean',
    'radish': 'daikon radish',
    'lettuce': 'lemongrass',
    'arugla': 'mizuna',
    'romaine': 'lemongrass',
    'spinach': 'water spinach',
    'celery': 'leaf celery',
    'bread': 'mantou',
    'cheese': 'ginger root',
    'onion': 'green onion',





}

original_to_chinese_utensils = {
    "fork": "chopsticks",
    "frying pan": "wok",
    "pan": "wok",
    "rice cooker": "donabe",
    "cooker": "donabe",
    "spatula": "chuan",
    "ladle": "hoak",
    "pot": "wok",
    "steamers": "bamboo steamers",
    "plate": "cleaver",
    "spatula": "wok shovel"
}