original_to_chinese_recipe_ing = {
    "tofu": "mapo tofu",
    "white rice": "jasmine scented rice",
    "corn": "bok choy",
    "ice cream": "baobing",
    "tea": "chinese tea",
    "sausage": "lap ceung",
    "salsa" : "mala sauce",
    "maple sauce" : "mala sauce",
    "maple syrup" : "chinese mala syrup",
    "spaghetti pasta": "lo mein",
    "spaghetti": "lo mein",
    "vinegar": "black vinegar",
    "red pepper flakes": "dried chili pepper",
    "italian parsley": "cilantro",
    "parmigiano-reggiano cheese": "fermented bean curd",
    "penne": "lo mein",
    "mushrooms": "shiitake mushrooms",
    "salad": "malatang",
    "quesadilla": "xian bing",
    "Burger": "chinese hamburger",
    "french pancake": "jian bing",
    "meat sauce": "da lu mian",
    "churro": "you tiao",
    "pizza": "scallion pancake",
    "wine": "shaoxing wine",
    "olive oil": "peanut oil",
    "burger": " chinese burger",
    "vegetable oil": "peanut oil",
    "canola oil": "peanut oil",
    "peanut oil": "peanut oil",
    "coconut oil": "peanut oil",
    "corn oil": "peanut oil",
    "sunflower oil": "peanut oil",
    "safflower oil": "peanut oil",
    "chicken nuggets": "chicken balls",
    "jerky": "bak kwa",
    "pork": "mapo doufu",
    "meat": "bakkwa",
    "lamb": "lamb broth",
    "pasta": "lo mein",
    "sauce": "hoisin sauce",
    "shrimp": "cha jang mein",

}

original_to_chinese_utensils = {
    "fork": "chopsticks",
    "frying pan": "wok",
    "pan": "wok",
    "rice cooker": "donabe",
    "cooker": "donabe",
    "spatula": "chuan",
    "ladle": "hoak",
    "pot": "wok",
    "steamers": "bamboo steamers",
    "plate": "cleaver",
    "spatula": "wok shovel"
}